title: Welcome to the Single Source Publishing Community
description: The Single Source Publishing Community (SSPC) is a network stakeholders from the Open Science community that are interested in Single Source Publishing (SSP) for scholarly purposes – developing open-source software and advocacy.  
tags:
  - single source publishing
  - publishing
  - open-source
  - open-science
  - research
  - education
plugins:
  - jekyll-seo-tag
twitter:
  username: mrchristian99
